*** empty log message ***
git-svn-id: https://ecell.svn.sourceforge.net/svnroot/ecell/ecell3/trunk@629 f1531174-cb10-0410-9fe6-89aa7ac3eedb

diff --git a/ecell/libecs/emtool.in b/ecell/libecs/emtool.in
--- a/ecell/libecs/emtool.in
+++ b/ecell/libecs/emtool.in
@@ -26,8 +26,8 @@ DMCOMPILE="${exec_prefix}/bin/dmcompile"
 INSUFFIX=".dm"
 SOSUFFIX=".so"
 
-#CPPSUFFIX=".cpp"
-#HPPSUFFIX=".hpp"
+CPPSUFFIX=".cpp"
+HPPSUFFIX=".hpp"
 
 unset DO_COMPILE DO_GENERATE DO_COMPILE
 
@@ -86,17 +86,23 @@ run_command()
 {
 	#echo $@
 	$@
-
-return $?
+	return $?
 }
 
 #at least one argument is required
 
 if [ -z $1 ] ;then 
-	$1
-	usage;
-	echo $1
-	exit 1
+    $1
+    help;
+    echo $1
+    exit 1
+fi
+
+# print help message
+ 
+if [ "$1" = "-h" -o "$1" = "--help" ] ; then
+    help
+    exit 0
 fi
 
 # get dynamic module class
@@ -104,54 +110,48 @@ fi
 CLASS=$1
 shift
 
-# print help message
- 
-if [ $CLASS = -h ] ; then 
-	help ; 
-	exit 0 ;
-fi
-
-
-TEMPLATEDIR="${prefix}/share/ecell/@VERSION@/template/$CLASS"
+TEMPLATEDIR="${prefix}/share/ecell/3.0.0/template/$CLASS"
 
 while true ; do
-	case "$1" in
-		-a|--all) DO_ALL=yes ; shift ; break ;;
-		-g|--generate) DO_GENERATE=yes ; shift ; break ;;
-		-c|--compile) DO_COMPILE=yes ; shift ; break ;;
-		-h|--help) help ; exit 0 ;;
-		*) echo "Internal error! " ; usage ; exit 1 ;;
-
-	esac
+    case "$1" in
+	-a|--all) DO_ALL=yes ; shift ; break ;;
+	-g|--generate) DO_GENERATE=yes ; shift ; break ;;
+	-c|--compile) DO_COMPILE=yes ; shift ; break ;;
+	-h|--help) help ; exit 0 ;;
+	*) echo "Internal error! " ; help ; exit 1 ;;
+    esac
 done
 
 #
-#initialize
+#initialize & get filename
 #
 
 initialize
 
-for file in $@ ; do
-	if [ `basename $file $INSUFFIX` != `basename $file` ] ; then
-		inputs="$inputs $file"
-	fi
-done
+inputfile=$1
 
 #
 #All dynamic module compile.
 #
 
 if [ $DO_ALL ] ; then 
-	for dmfile in $inputs;  do
-		base=`basename $dmfile $INSUFFIX`
-		sofile=$base$SOSUFFIX
-		
-		run_command "cp $dmfile $ETTMPDIR"
-		run_command "pushd $ETTMPDIR"
-		run_command "$DMGEN $base.dm -t $TEMPLATEDIR"
-		run_command "popd"
-		run_command "$DMCOMPILE $ETTMPDIR/$base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE" 
-	done
+    
+    base=`basename $inputfile .dm`
+    sofile=$base$SOSUFFIX
+    
+    if [ -f $sofile -a $sofile -nt $inputfile ] ; then
+	echo -n "$sofile is newer than &inputfile." 
+	echo "skipping."
+	cleanup
+	exit 0
+    fi
+
+    run_command "cp $inputfile $ETTMPDIR"
+    run_command "pushd $ETTMPDIR"
+    run_command "$DMGEN $base.dm -t $TEMPLATEDIR"
+    run_command "popd"
+    run_command "$DMCOMPILE $ETTMPDIR/$base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I. -I.." 
+
 fi
 
 #
@@ -159,30 +159,43 @@ fi
 #
 
 if [ $DO_GENERATE ] ; then 
-	for dmfile in $inputs;  do
-		base=`basename $dmfile $INSUFFIX`
-		sofile=$base$SOSUFFIX
+    
+    base=`basename $inputfile .dm`
+    cppfile=$base$CPPSUFFIX
 
-		run_command "$DMGEN $base.dm -t $TEMPLATEDIR"
-	done
+    if [ -f $cppfile -a $cppfile -nt $inputfile ] ; then
+	echo -n "$cppfile is newer than $inputfile." 
+	echo "skipping."
+	cleanup
+	exit 0
+    fi
+
+    run_command "$DMGEN $base.dm -t $TEMPLATEDIR"
+    
 fi
 
 #
 #Compile cpp to so file.
 #
 
-if [ $DO_COMPILE ] ; then 
-	for cppfile in $inputs;  do
-		base=`basename $cppfile $INSUFFIX`
-		
-		run_command "cp $cppfile $ETTMPDIR"
-		run_command "$DMCOMPILE $ETTMPDIR/$base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
-	done
+if [ $DO_COMPILE  ] ; then 
+	
+    base=`basename $inputfile .cpp`	     			
+    sofile=$base$SOSUFFIX
+
+    if [ -f $sofile -a $sofile -nt $ ] ; then
+	echo "$sofile is newer than $inputfile..." 
+	echo "skipping..."
+	cleanup
+	exit 0
+    fi
+
+    run_command "$DMCOMPILE $base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
+
 fi
 
-
 #
-#cleanup
+#cleanup & exit
 #
 
 cleanup
