new options -v, -T etc, error check, cleanups
git-svn-id: https://ecell.svn.sourceforge.net/svnroot/ecell/ecell3/trunk@859 f1531174-cb10-0410-9fe6-89aa7ac3eedb

diff --git a/ecell/libecs/emtool.in b/ecell/libecs/emtool.in
--- a/ecell/libecs/emtool.in
+++ b/ecell/libecs/emtool.in
@@ -15,6 +15,7 @@ pythondir=@pythondir@
 
 BINDIR="${exec_prefix}/bin"
 ECELL_INCLUDE="${prefix}/include/ecell"
+LIBECS_INCLUDE="${ECELL_INCLUDE}/libecs"
 
 CXX="c++"
 MV="/bin/mv"
@@ -28,7 +29,7 @@ SOSUFFIX=".so"
 CPPSUFFIX=".cpp"
 HPPSUFFIX=".hpp"
 
-unset DO_COMPILE DO_GENERATE DO_COMPILE
+unset DO_COMPILE DO_GENERATE VERBOSE
 
 TMPDIR="/tmp"
 ETTMPDIR="$TMPDIR/emtool.$$"
@@ -52,14 +53,16 @@ usage
 cat << EOT_HELP
 
 Options:
-	-a or --all)	        Create a so file from a dm file.
-	-g or --generate)       Generate a .cpp file from a dm file.
-	-c or --compile)        Compile a .cpp file.
-        -C or --class)          Specify a template class.
-        -t or --template)       Specify a dmgen template file.
-	-i or --include)        Specify a dmcompile include file.
-        -m or --munch)          Specify munch file.
-        -h or --help)		Print this message.
+	-a or --all                 Create a so file from a dm file.
+	-g or --generate            Only generate a .cpp file from a dm file.
+	-c or --compile             Only compile a .cpp file.
+        -t or --template file       Specify a dmgen template file.
+        -T or --type type           Specify a template type.
+	-i or --include directory   Specify a dmcompile include file.
+        -m or --munch file          Specify munch file.
+        -v or --verbose   	    Be verbose.
+        -h or --help		    Print this message.
+
 
 This program is part of E-CELL Simulation Environment Version 3.
 Written by Tomoya Kitayama <tomo@e-cell.org>
@@ -85,19 +88,28 @@ interrupted()
 	exit 1
 }
 
+message()
+{
+    if [ $VERBOSE ] ; then
+	echo $@
+    fi
+}
+
 run_command()
 {
-	echo $@
+    message $@
+
+    if [ $VERBOSE ] ; then
 	$@
-	return $?
+    else
+	$@ > /dev/null
+    fi
 }
 
 #at least one argument is required
 
 if [ -z $1 ] ;then 
-    $1
     help;
-    echo $1
     exit 1
 fi
 
@@ -111,19 +123,20 @@ fi
 # get dynamic module class
 
 #default class is reactor
-CLASS='reactor'
+TYPE='reactor'
 
-TEMPLATEDIR="${prefix}/share/ecell/@VERSION@/template/$CLASS"
+TEMPLATEDIR="${prefix}/share/ecell/@VERSION@/template/$TYPE"
 
 while [ -n "$(echo $1 | grep '-')" ]; do
     case "$1" in
-	-a|--all) DO_ALL=yes ; shift ; break ;;
-	-g|--generate) DO_GENERATE=yes ; shift ; break ;;
-	-C|--class) CLASS=$2 ; shift ; break ;;
-	-c|--compile) DO_COMPILE=yes ; shift ; break ;;
-	-t|--template) DO_TEMPLATE=yes ; templatefile=$2 ; shift 2 ;;
-	-i|--include) DO_INCLUDE=yes ; includefile=$2 ; shift 2;;
-	-m|--munch) DO_MUNCH=yes ; MUNCHFILE=$2 ; shift 2 ;;
+	-a|--all) DO_ALL=yes ; shift ;;
+	-g|--generate) DO_GENERATE=yes ; shift ;;
+	-T|--type) TYPE=$2 ; shift ;;
+	-c|--compile) DO_COMPILE=yes ; shift ;;
+	-t|--template) HAVE_TEMPLATE=yes ; templatefile=$2 ; shift 2 ;;
+	-i|--include) HAVE_INCLUDE=yes ; includedir=$2 ; shift 2 ;;
+	-m|--munch) HAVE_MUNCH=yes ; MUNCHFILE=$2 ; shift 2 ;;
+	-v|--verbose) VERBOSE=yes ; shift ;;
 	-h|--help) help ; exit 0 ;;
 	*) echo "Invarid Option! " ; help ; exit 1 ;;
     esac
@@ -135,81 +148,47 @@ done
 
 initialize
 
-inputfile=$1
-
-#
-#All dynamic module compile.
-#
-
 if [ $DO_ALL ] ; then 
-    
-    base=`basename $inputfile .dm`
-    sofile=$base$SOSUFFIX
-    
-    if [ -f $sofile -a $sofile -nt $inputfile ] ; then
-	echo -n "$sofile is newer than $inputfile " 
-	echo "skipping."
-	cleanup
-	exit 0
-    fi
-    
-    if [ $DO_TEMPLATE ] ; then 
-	if [ $DO_MUNCH ] ; then 
-	    run_command "$DMGEN $CLASS -d $inputfile -t $templatefile -m $munchfile"
-	else
-	    run_command "$DMGEN $CLASS -d $inputfile -t $templatefile"
-        fi
-    else
-	if [ $DO_MUNCH ] ; then 
-	    run_command "$DMGEN $CLASS -d $inputfile -m $munchfile"
-	else
-	    run_command "$DMGEN $CLASS -d $inputfile"
-        fi
-    fi    
-
-    if [ $DO_INCLUDE ] ; then 
-	run_command "$DMCOMPILE $base.cpp -I $includefile -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
-    else
-	run_command "$DMCOMPILE $base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
-    fi
-
-    run_command rm $base.cpp
-    echo "generate $base.so"
+    DO_GENERATE=yes
+    DO_COMPILE=yes
 fi
 
+inputfile=$1
+base=`basename $inputfile .dm`
+base=`basename $base .cpp`
+cppfile=$base$CPPSUFFIX
+sofile=$base$SOSUFFIX
+
+
+
 #
-#Generate dm to cpp/hpp source file.
+# dm to cpp/hpp source file.
 #
 
 if [ $DO_GENERATE ] ; then 
     
-    base=`basename $inputfile .dm`
-    cppfile=$base$CPPSUFFIX
+    command_string="$DMGEN $TYPE -d $inputfile"
 
-    if [ -f $cppfile -a $cppfile -nt $inputfile ] ; then
-	echo -n "$cppfile is newer than $inputfile " 
-	echo "skipping."
-	cleanup
-	exit 0
+    if [ $HAVE_TEMPLATE ] ; then 
+	command_string="$command_string -t $templatefile"
     fi
 
-    if [ $DO_TEMPLATE ] ; then 
-	if [ $DO_MUNCH ] ; then 
-	    run_command "$DMGEN $CLASS -d $inputfile -t $templatefile -m $munchfile"
-	else
-	    run_command "$DMGEN $CLASS -d $inputfile -t $templatefile"
-	fi
+    if [ $HAVE_MUNCH ] ; then 
+	command_string="$command_string -m $munchfile"
+    fi
 
+    if run_command $command_string ; then
+	message "generated $base.cpp"
     else
-	if [ $DO_MUNCH ] ; then 
-	    run_command "$DMGEN $CLASS -d $inputfile -m $munchfile"
-	else
-	    run_command "$DMGEN $CLASS -d $inputfile"
-	fi
+	echo "error occured in code generation stage."
+	cleanup
+	exit 1
     fi
 
-    echo "generate $base.cpp"
+    unset command_string
+
 fi
+
 
 #
 #Compile cpp to so file.
@@ -217,23 +196,21 @@ fi
 
 if [ $DO_COMPILE  ] ; then 
 	
-    base=`basename $inputfile .cpp`	     			
-    sofile=$base$SOSUFFIX
+    command_string="$DMCOMPILE $base.cpp -I $ECELL_INCLUDE -I $LIBECS_INCLUDE -I . -I .."     
 
-#    if [ -f $sofile -a $sofile -nt $ ] ; then
-#	echo "$sofile is newer than $inputfile..." 
-#	echo "skipping..."
-#	cleanup
-#	exit 0
-#    fi
-
-    if [ $DO_INCLUDE ] ; then 
-	run_command "$DMCOMPILE $base.cpp -I $includefile -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
-    else
-	run_command "$DMCOMPILE $base.cpp -I $ECELL_INCLUDE -I $EMTOOL_INCLUDE -I . -I .." 
+    if [ $HAVE_INCLUDE ] ; then 
+	command_string="$command_string -I $includedir"
     fi
 
-    echo "generate $base.so"
+    if run_command $command_string ; then
+	message "generated $base.so"
+    else
+	echo "error occured in compiling stage."
+	cleanup
+	exit 1
+    fi
+
+    unset command_string
 fi
 
 #
